Events/urls.py
from django.urls import path
from . import views
from Events.views import Events,AddEvent

app_name = 'story6'

urlpatterns=[
    path('',Events,name="Events"),
    path('AddEvent',AddEvent,name='AddEvent')
]

main/urls.py
from django.urls import path,include

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('about', views.about, name='about'),
    path('educations', views.educations, name='educations'),
    path('experiences', views.experiences, name='experiences'),
    path('project', views.project, name='project'),
    path('story1', views.story1, name='story1'),
    path('contact', views.contact, name='contact'),
    path('story5/', include('story5.urls',namespace='story5')),
    path('Events/', include('Events.urls',namespace='Events')),
]

story4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('story5/', include('story5.urls')),
    path('Events/', include('Events.urls',namespace='Events')),
]

Events/models.py
from django.db import models

# Create your models here.

class FormMember(models.Model):
    FirstName = models.CharField(max_length=20)
    LastName = models.CharField(max_length=20)

    def __str__(self):
        return self.FirstName

class FormEvent(models.Model):
    EventName = models.CharField(max_length=20)

    def __str__(self):
        return self.EventName

Events/forms.py
from django.forms import ModelForm
from django import forms
from .models import FormEvent,FormMember

class EventForm(forms.ModelForm):
    class Meta:
        model = FormEvent
        fields = [
            'EventName',
        ]

        widgets = {
            'Course' : forms.TextInput(
                attrs={
                    'class':'form-control',
                    'placeholder':'Enter Course',
                    'style':'#FF0C55',
                    'id':'Course',
                    'name':'Course',
                    
                }
            ),
            'Lecturer' : forms.TextInput(
                attrs={
                    'class':'form-control',
                    'placeholder':'Enter Lecturer',
                    'style':'#FF0C55',
                    'id':'Lecturer',
                    'name':'Lecturer',
                    
                }
            ),
            'Credit' : forms.Select(
                attrs={
                    'class':'form-control',
                    'placeholder':'Enter Course',
                    'style':'#FF0C55',
                    'id':'Credit',
                    'name':'Credit',
                    
                }
            ),
            'Semester' : forms.Select(
                attrs={
                    'class':'form-control',
                    'placeholder':'Enter Course',
                    'style':'#FF0C55',
                    'id':'Semester',
                    'name':'Semester',
                    
                }
            ),
            'Description' : forms.Textarea(
                attrs={
                    'class':'form-control',
                    'placeholder':'Enter Course Description',
                    'style':'#FF0C55',
                    'id':'Description',
                    'name':'Description',
                    
                }
            )
        }

Events/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import EventForm
from .models import FormMember,FormEvent

# Create your views here.
response={}
def Events(request):
    return render(request,'Events/AddEvent.html',response)

def AddEvent(request):
    model = FormEvent
    form = EventForm(request.POST or None)

    if(request.method=='POST' and form.is_valid()):
        response['EventName']=request.POST['Event']
        Event = EventForm(EventName=response['EventName'])
        Event.save()
        return HttpResponseRedirect('')
    else:
        return HttpResponseRedirect('')
    
    return render(request,'Events/AddEvent.html',response)  

Events/templates/Events/AddEvent.html
{% extends 'base.html' %}

{% load static %}

<html>

    
        {% block header1 %}
        <body class="body">
            <h1 class="h1">
                <a href="#"><span id="span">KAYSA SWA</span></a>
                <ul></ul>
                <a href="{% url 'Events:AddEvent' %}">
                    <button id="buttonpink" type="button" class="btn btn-secondary">ADD EVENTS</button></a>
                
                <a href="{% url 'Events:Events' %}">
                    <button id="buttonorange" type="button" class="btn btn-secondary">EVENTS</button></a>

            </h1>

        {% endblock header1 %}

        {% block content %}
            <h2 id='font-color' class='center'>EVENTS</h2>

            <h3 class="center">
                <div class="row" style="padding: 20px;display: flex;justify-content: center;">
                    <div class="col-sm-6">
                      <div class="card">
                        <div class="card-body">
                          <h3 class="card-title">EVENT NAME</h3>
                            <p class="card-text">MEMBER</p>
                          <a href="#" class="btn btn-primary" style="background: linear-gradient(90deg, #F17B41 , #CD4BC9, #E56487);">JOIN US</a>
                        </div>
                      </div>
                    </div>   
            </div>
        </h3>

    {% endblock content %}
        
       
        {% block header3 %}

            <h3 class="h3">FIND ME HERE
                <script src="https://kit.fontawesome.com/56fc67844f.js" crossorigin="anonymous"></script>
                    <div class="center">
                        <a href="https://www.instagram.com/kaysasy_/" target="_blank">
                            <i class="fab fa-instagram" id="link2"></i></a>
        
                            <a href="https://id.linkedin.com/in/kaysa-swa-20814b1a4" target="_blank">
                            <i class="fab fa-linkedin"  id="link1"></i></a>
                            
                            <a href="https://mail.google.com/mail/u/0/#inbox?compose=NZVHGDkdRDwnxgckKZgqFpxfFnMBqkGrVcSHCSVPWVZvKrMTHhQHhLjRXBvCxjmkFjVNpg" target="_blank">
                            <i class="fas fa-envelope" id="link1"></i></a>
                            
                            <i class="fab fa-line" id="link1"></i>
                    </div>
            </h3>

        {% endblock header3 %}
        
  

            </h4>

             
                
            </h4>
        </body>
</html>

Events/templates/Events/Events.html
{% extends 'base.html' %}

{% load static %}

<html>

    
        {% block header1 %}
        <body class="body">
            <h1 class="h1">
                <a href="#"><span id="span">KAYSA SWA</span></a>
                <ul></ul>
                <a href="{% url 'Events:AddEvent' %}">
                    <button id="buttonpink" type="button" class="btn btn-secondary">ADD EVENT</button></a>
                
                <a href="{% url 'Events:Events' %}">
                    <button id="buttonorange" type="button" class="btn btn-secondary">EVENTS</button></a>

            </h1>

        {% endblock header1 %}

        {% block content %}
            <h2 id='font-color' class='center'>EVENTS</h2>

            <h3 class="center">
                <div class="row" style="padding: 20px;display: flex;justify-content: center;">
                    <div class="col-sm-6">
                      <div class="card">
                        <div class="card-body">
                          <h3 class="card-title">EVENT NAME</h3>
                            <p class="card-text">MEMBER</p>
                          <a href="#" class="btn btn-primary" style="background: linear-gradient(90deg, #F17B41 , #CD4BC9, #E56487);">JOIN US</a>
                        </div>
                      </div>
                    </div>   
            </div>
        </h3>

    {% endblock content %}
        
       
        {% block header3 %}

            <h3 class="h3">FIND ME HERE
                <script src="https://kit.fontawesome.com/56fc67844f.js" crossorigin="anonymous"></script>
                    <div class="center">
                        <a href="https://www.instagram.com/kaysasy_/" target="_blank">
                            <i class="fab fa-instagram" id="link2"></i></a>
        
                            <a href="https://id.linkedin.com/in/kaysa-swa-20814b1a4" target="_blank">
                            <i class="fab fa-linkedin"  id="link1"></i></a>
                            
                            <a href="https://mail.google.com/mail/u/0/#inbox?compose=NZVHGDkdRDwnxgckKZgqFpxfFnMBqkGrVcSHCSVPWVZvKrMTHhQHhLjRXBvCxjmkFjVNpg" target="_blank">
                            <i class="fas fa-envelope" id="link1"></i></a>
                            
                            <i class="fab fa-line" id="link1"></i>
                    </div>
            </h3>

        {% endblock header3 %}
        
  

            </h4>

             
                
            </h4>
        </body>
</html>