Events/urls.py
from django.urls import path
from . import views
from Events.views import Events,AddEvent

app_name = 'story6'

urlpatterns=[
    path('',Events,name="Events"),
    path('AddEvent',AddEvent,name='AddEvent')
]

main/urls.py
from django.urls import path,include

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('about', views.about, name='about'),
    path('educations', views.educations, name='educations'),
    path('experiences', views.experiences, name='experiences'),
    path('project', views.project, name='project'),
    path('story1', views.story1, name='story1'),
    path('contact', views.contact, name='contact'),
    path('story5/', include('story5.urls',namespace='story5')),
    path('Events/', include('Events.urls',namespace='Events')),
]

story4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('story5/', include('story5.urls')),
    path('Events/', include('Events.urls',namespace='Events')),
]

story5/urls.py
from django.urls import path

from . import views
from .views import courses,addcourse,detailcourse,deletecourse

app_name = 'story5'

urlpatterns = [
    path('', courses.as_view(), name='courses'),
    path('addcourse', views.addcourse, name='addcourse'),
    path('detailcourse/<pk>/',detailcourse.as_view(),name='detailcourse'),
    path('deletecourse/(?P<delete_id>[0-9])',views.deletecourse,name='deletecourse')
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render


def home(request):
    page = 'HOME'
    response = {'title' : page}
    return render(request,'main/HOME1.html',response)

def about(request):
    page = 'ABOUT ME'
    response = {'title' : page}
    return render(request,'main/ABOUT ME1.html',response)

def educations(request):
    page = 'EDUCATIONS'
    response = {'title' : page}
    return render(request,'main/EDUCATIONS1.html',response)

def experiences(request):
    page = 'EXPERIENCES'
    response = {'title' : page}
    return render(request,'main/EXPERIENCES1.html',response)

def project(request):
    page = 'PROJECT'
    response = {'title' : page}
    return render(request,'main/PROJECT1.html',response)

def story1(request):
    page = 'STORY1'
    response = {'title' : page}
    return render(request,'main/Biodata.html',response)

def contact(request):
    page = 'CONTACT'
    response = {'title' : page}
    return render(request,'main/CONTACT1.html',response)

main/templates/main/ABOUT ME1.html
{% extends 'base.html' %}

{% load static %}

<html>



    

            {% block header1 %}
            <body class="body">
            <h1 class="h1">
                <a href="{% url 'main:home' %}"><span id="span">KAYSA SWA</span></a>
                <ul></ul>
                    <a href="{% url 'main:home' %}">
                    <button id="buttonpink" type="button" class="btn btn-secondary">HOME</button></a>

                    <a href="{% url 'main:about' %}">
                    <button id="buttonorange" type="button" class="btn btn-secondary">ABOUT ME</button></a>

                    <a href="{% url 'main:educations' %}">
                    <button id="buttonpink" type="button" class="btn btn-secondary">EDUCATIONS</button></a>

                    <a href="{% url 'main:experiences' %}">
                    <button id="buttonorange" type="button" class="btn btn-secondary">EXPERIENCES</button></a>

                    <a href="{% url 'main:project' %}">
                    <button id="buttonpink" type="button" class="btn btn-secondary">PROJECT</button></a>

                    <a href="{% url 'main:contact' %}">
                    <button id="buttonorange" type="button" class="btn btn-secondary">CONTACT</button></a>

            </h1>

        {% endblock header1 %}

        {% block content %}

            <h2 class="h2">
                <div class="img">
                    <img src="{% static 'img/MINGYU7.jpg' %}" alt="mingyuimage" class="centre" id="imgaboutme"> 
                </div>
                
                <div class="shape">
                    <span id="p">
                        Hello everyone, thank you so much for visiting my page. 
                        <ul></ul>
                        I’m Kaysa Syifa Wijdan Amin. I’m 19 years old.
                        <ul></ul>
                        I study Computer Science at the University of Indonesia. 
                        <ul></ul>
                        In the future, I will post my work, my project, and my accomplishment here.
                        <ul></ul>
                        Please wait for it!!
                    </span>
                </div>
                
            </h2>

        {% endblock content %}

        {% block header3 %}

            <h3 class="h3">FIND ME HERE
                <script src="https://kit.fontawesome.com/56fc67844f.js" crossorigin="anonymous"></script>
                    <div class="center">
                        <a href="https://www.instagram.com/kaysasy_/" target="_blank">
                            <i class="fab fa-instagram" id="link2"></i></a>
        
                            <a href="https://id.linkedin.com/in/kaysa-swa-20814b1a4" target="_blank">
                            <i class="fab fa-linkedin"  id="link1"></i></a>
                            
                            <a href="https://mail.google.com/mail/u/0/#inbox?compose=NZVHGDkdRDwnxgckKZgqFpxfFnMBqkGrVcSHCSVPWVZvKrMTHhQHhLjRXBvCxjmkFjVNpg" target="_blank">
                            <i class="fas fa-envelope" id="link1"></i></a>
                            
                            <i class="fab fa-line" id="link1"></i>
                    </div>
            </h3>
        
        {% endblock header3 %}
  

            </h4>
              
            </h4>
        </body>

    </html>

    

main/templates/main/Biodata.html
{% load static %}


<html>
    <head>
        <title>RESUME</title>
        <style>
            .header {
                padding: 40px;
                text-align: center;
                background: #1abc9c;
                color: white;
                font-size: 20px;
            }

            .header2 {
                box-shadow: 4px 4px 4px #1abc9c;
                padding: 40px;
                text-align: center;
                background: #ffffff;
                font-size: 10px;
                font-family:'Courier New';
            }

            .content {
                padding: 40px;
                text-align: center;
                background: #1abc9c;
                color: white;
                font-size: 10px;
            }

            .paragraph {
                font-size: 15px;
                font-family:'Courier New';
            
            }

            .centre {
                margin-left: auto;
                margin-right: auto;
            }
            
            
        
        </style>
    </head>
    <body>
        <div class="header">
            <h1 style="text-align:center;font-family:'Courier New'">Kaysa Syifa Wijdan Amin</h1>
            <p style="text-align:center;font-family:'Courier New'">1906400362</p>
            <p style="text-align:center;font-family:'Courier New'">Computer Science Student at Universitas Indonesia</p>
        </div>

        <div class="header2">
                <img src="{% static 'img/MINGYU25.jpg' %}" alt="mingyuimage" class="centre" width="200" height="200">
                <h1><font color="green">ABOUT ME</h1></font>
            <p class="paragraph"> I'm a second year computer science student. I already learn java and python programming language and now I'm learning about html. I'm a first born in my family. I have one little brother.
                As a big sister and the first born, I need to set great example for my little brother. I need to be a person that could makes my parents life and everyone life's easier.
                I'm a hardworking student. I always try to think positively and try to learn everything that I could. 
            </p>
            <p class="paragraph"> I have hobbies that I do when I have some time off to refresh my mind, which are listening to music, 
                swimming, sleeping, watching k-dramas, movies, variety shows, and travelling or get out of the house to a coffe shop. 
                I do all of those things when I got spare time off, this makes me always set my mind to enjoy my life more despite all of the homework 
                that I should do.
            </p>
            <script src="https://kit.fontawesome.com/56fc67844f.js" crossorigin="anonymous"></script>
            <i class="fab fa-line" style="font-size:20px"></i><span class="paragraph">kaysa4701</span>
            <i class="fab fa-instagram" style="font-size:20px;padding-left:25px"></i><span class="paragraph">kaysasy_</span>
            <i class="far fa-envelope" style="font-size:20px;padding-left:25px"></i><span class="paragraph">kaysa.syifa@ui.ac.id</span>
            <i class="fas fa-phone-square-alt" style="font-size:20px;padding-left:25px"></i><span class="paragraph">087871055279</span>
            
        </div>

        
        <div class="content">
            <h1 style="text-align:center;font-family:'Courier New'">Riwayat Pendidikan</h1>
            <center><table width = "50%"></center>
                <tr>
                    <td class="paragraph"><font color="white">Universitas Indonesia</td></font>
                    <td class="paragraph"><font color="white">2019 - 2020</td></font>
                </tr>
                <tr>
                    <td class="paragraph"><font color="white">SMAN 86 Jakarta</td></font>
                    <td class="paragraph"><font color="white">2016 - 2019</td></font>
                </tr>
                <tr>
                    <td class="paragraph"><font color="white">SMPN 177 Jakarta</td></font>
                    <td class="paragraph"><font color="white">2013 - 2016</td></font>
                </tr>
                <tr>
                    <td class="paragraph"><font color="white">SDN 01 Pagi</td></font>
                    <td class="paragraph"><font color="white">2007 - 2013</td></font>
                </tr>
            </table>
    </div>
        
    </body>
</html>

main/templates/main/CONTACT1.html
{% extends 'base.html' %}

{% load static %}

<html>
    


        
        {% block header1 %}
        <body class="body">
            <h1 class="h1">
                <a href="{% url 'main:home' %}"><span id="span">KAYSA SWA</span></a>
                <ul></ul>
                    <a href="{% url 'main:home' %}">
                    <button id="buttonpink" type="button" class="btn btn-secondary">HOME</button></a>

                    <a href="{% url 'main:about' %}">
                    <button id="buttonorange" type="button" class="btn btn-secondary">ABOUT ME</button></a>

                    <a href="{% url 'main:educations' %}">
                    <button id="buttonpink" type="button" class="btn btn-secondary">EDUCATIONS</button></a>

                    <a href="{% url 'main:experiences' %}">
                    <button id="buttonorange" type="button" class="btn btn-secondary">EXPERIENCES</button></a>

                    <a href="{% url 'main:project' %}">
                    <button id="buttonpink" type="button" class="btn btn-secondary">PROJECT</button></a>

                    <a href="{% url 'main:contact' %}">
                    <button id="buttonorange" type="button" class="btn btn-secondary">CONTACT</button></a>

            </h1>

        {% endblock header1 %}


        {% block header3 %}
    
            <h2 class="h2contact">FIND ME HERE
                <script src="https://kit.fontawesome.com/56fc67844f.js" crossorigin="anonymous"></script>
                <div class="center">
                    <a href="https://www.instagram.com/kaysasy_/" target="_blank">
                        <i class="fab fa-instagram" id="link2"></i></a>

                        <a href="https://id.linkedin.com/in/kaysa-swa-20814b1a4" target="_blank">
                        <i class="fab fa-linkedin"  id="link1"></i></a>
                        
                        <a href="https://mail.google.com/mail/u/0/#inbox?compose=NZVHGDkdRDwnxgckKZgqFpxfFnMBqkGrVcSHCSVPWVZvKrMTHhQHhLjRXBvCxjmkFjVNpg" target="_blank">
                        <i class="fas fa-envelope" id="link1"></i></a>
                        
                        <i class="fab fa-line" id="link1"></i>
                </div>
            </h2>

        {% endblock header3 %}
  

            </h3>
           

            </h3>
        </body>
    </html>

main/templates/main/EDUCATIONS1.html
{% extends 'base.html' %}

{% load static %}


<html>
   



  
    {% block header1 %}
    <body class="body">
            <h1 class="h1">
                <a href="{% url 'main:home' %}"><span id="span">KAYSA SWA</span></a>
                <ul></ul>
                    <a href="{% url 'main:home' %}">
                    <button id="buttonpink" type="button" class="btn btn-secondary">HOME</button></a>

                    <a href="{% url 'main:about' %}">
                    <button id="buttonorange" type="button" class="btn btn-secondary">ABOUT ME</button></a>

                    <a href="{% url 'main:educations' %}">
                    <button id="buttonpink" type="button" class="btn btn-secondary">EDUCATIONS</button></a>

                    <a href="{% url 'main:experiences' %}">
                    <button id="buttonorange" type="button" class="btn btn-secondary">EXPERIENCES</button></a>

                    <a href="{% url 'main:project' %}">
                    <button id="buttonpink" type="button" class="btn btn-secondary">PROJECT</button></a>

                    <a href="{% url 'main:contact' %}">
                    <button id="buttonorange" type="button" class="btn btn-secondary">CONTACT</button></a>

            </h1>

        {% endblock header1 %}
              
    
   
    {% block content %}
        <h2>
            <table class="tableed">
                <tr>
                    <td id="tded"><font id="span">University of Indonesia</td></font>
                    <td id="tded"><font id="span">2019 - Present</td></font>
                </tr>
                <tr>
                    <td id="tded"><font id="span">86 HighSchool Jakarta</td></font>
                    <td id="tded"><font id="span">2016 - 2019</td></font>
                </tr>
                <tr>
                    <td id="tded"><font id="span">177 MiddleSchool Jakarta</td></font>
                    <td id="tded"><font id="span">2013 - 2016</td></font>
                </tr>
            </table>
        </h2>

        {% endblock content %}
        
        {% block header3 %}

            <h3 class="h3">FIND ME HERE
                <script src="https://kit.fontawesome.com/56fc67844f.js" crossorigin="anonymous"></script>
                    <div class="center">
                        <a href="https://www.instagram.com/kaysasy_/" target="_blank">
                            <i class="fab fa-instagram" id="link2"></i></a>
        
                            <a href="https://id.linkedin.com/in/kaysa-swa-20814b1a4" target="_blank">
                            <i class="fab fa-linkedin"  id="link1"></i></a>
                            
                            <a href="https://mail.google.com/mail/u/0/#inbox?compose=NZVHGDkdRDwnxgckKZgqFpxfFnMBqkGrVcSHCSVPWVZvKrMTHhQHhLjRXBvCxjmkFjVNpg" target="_blank">
                            <i class="fas fa-envelope" id="link1"></i></a>
                            
                            <i class="fab fa-line" id="link1"></i>
                    </div>
            </h3>
        
        {% endblock header3 %}
  

            </h4>
        
         
            </h4>
   

    </body>
</html>

main/templates/main/EXPERIENCES1.html
{% extends 'base.html' %}

{% load static %}


<html>
  
    

    
    {% block header1 %}
    <body class="body">
            <h1 class="h1">
                <a href="{% url 'main:home' %}"><span id="span">KAYSA SWA</span></a>
                <ul></ul>
                    <a href="{% url 'main:home' %}">
                    <button id="buttonpink" type="button" class="btn btn-secondary">HOME</button></a>

                    <a href="{% url 'main:about' %}">
                    <button id="buttonorange" type="button" class="btn btn-secondary">ABOUT ME</button></a>

                    <a href="{% url 'main:educations' %}">
                    <button id="buttonpink" type="button" class="btn btn-secondary">EDUCATIONS</button></a>

                    <a href="{% url 'main:experiences' %}">
                    <button id="buttonorange" type="button" class="btn btn-secondary">EXPERIENCES</button></a>

                    <a href="{% url 'main:project' %}">
                    <button id="buttonpink" type="button" class="btn btn-secondary">PROJECT</button></a>

                    <a href="{% url 'main:contact' %}">
                    <button id="buttonorange" type="button" class="btn btn-secondary">CONTACT</button></a>

            </h1>

        {% endblock header1 %}
    
    {% block content %}


        <h2>
            <table id="tableex" class="img">
                <tr>
                    <td id="td"> 
                        <img src="{% static 'img/perak.jpg' %}" alt="perakimage" class="centre"  id="imgex">
                        <span id="spantable"> Staff of Sponsorship </span>
                    </td>
                    <td id="td">
                        <img src="{% static 'img/compfest.jpg' %}" alt="compfestimage" class="centre" id="imgex">
                        <span id="spantable">Staff of Data Science Academy</span></td>
                </tr>

                <ul></ul>
                
                <tr>
                    <td id="td"> 
                        <img src="{% static 'img/dpm.jpg' %}" alt="dpmimage" class="centre" id="imgex" >
                        <span id="spantable">Staff of Human Resources</span></td>
                    <td id="td">
                        <img src="{% static 'img/siwakng.png' %}" alt="siwakngimage" class="centre" id="imgex" >
                        <span id="spantable">Staff of Human Resources</span></td>
                </tr>
                
            </table>

        </h2>

        
    {% endblock content %}
        
       
        {% block header3 %}

            <h3 class="h3">FIND ME HERE
                <script src="https://kit.fontawesome.com/56fc67844f.js" crossorigin="anonymous"></script>
                    <div class="center">
                        <a href="https://www.instagram.com/kaysasy_/" target="_blank">
                            <i class="fab fa-instagram" id="link2"></i></a>
        
                            <a href="https://id.linkedin.com/in/kaysa-swa-20814b1a4" target="_blank">
                            <i class="fab fa-linkedin"  id="link1"></i></a>
                            
                            <a href="https://mail.google.com/mail/u/0/#inbox?compose=NZVHGDkdRDwnxgckKZgqFpxfFnMBqkGrVcSHCSVPWVZvKrMTHhQHhLjRXBvCxjmkFjVNpg" target="_blank">
                            <i class="fas fa-envelope" id="link1"></i></a>
                            
                            <i class="fab fa-line" id="link1"></i>
                    </div>
            </h3>

        {% endblock header3 %}
        
  

            </h4>

             
                
            </h4>
   </body>
   </html>

main/templates/main/HOME1.html
{% extends 'base.html' %}

{% load static %}

<html>


    {% block header1 %}
    <body class="body">
            <h1 class="h1hello">HELLO,</h1>
            
            <h1 class="h1kay">I'M KAYSA</h1>
            
            <h1>
                <a href="{% url 'main:home' %}">
                <button id="buttonhomepink" type="button" class="btn btn-secondary">HOME</button></a>
                <a href="{% url 'main:about' %}">
                <button id="buttonhomeorange" type="button" class="btn btn-secondary">ABOUT ME</button></a>
                <a href="{% url 'main:educations' %}">
                <button id="buttonhomepink2" type="button" class="btn btn-secondary">EDUCATIONS</button></a>
                <a href="{% url 'main:experiences' %}">
                <button id="buttonhomeorange2" type="button" class="btn btn-secondary">EXPERIENCES</button></a>
                <a href="{% url 'main:project' %}">
                <button id="buttonhomepink3" type="button" class="btn btn-secondary">PROJECT</button></a>
                <a href="{% url 'main:contact' %}">
                <button id="buttonhomeorange3" type="button" class="btn btn-secondary">CONTACT</button></a>
            </h1>

    {% endblock header1 %}
    
        {% block header3 %}
        
            <h2 class="h2home">FIND ME HERE
                <script src="https://kit.fontawesome.com/56fc67844f.js" crossorigin="anonymous"></script>
                <div class="center">
                    <a href="https://www.instagram.com/kaysasy_/" target="_blank">
                        <i class="fab fa-instagram" id="link2"></i></a>
    
                        <a href="https://id.linkedin.com/in/kaysa-swa-20814b1a4" target="_blank">
                        <i class="fab fa-linkedin"  id="link1"></i></a>
                        
                        <a href="https://mail.google.com/mail/u/0/#inbox?compose=NZVHGDkdRDwnxgckKZgqFpxfFnMBqkGrVcSHCSVPWVZvKrMTHhQHhLjRXBvCxjmkFjVNpg" target="_blank">
                        <i class="fas fa-envelope" id="link1"></i></a>
                        
                        <i class="fab fa-line" id="link1"></i>
                </div>
            </h2>

        {% endblock header3 %}

            </h3>
             
            </h3>
        </body>
   
</html>
        

main/templates/main/PROJECT1.html
{% extends 'base.html' %}

{% load static %}

<html>


        {% block header1 %}
        <body class="body">
            <h1 class="h1">
                <a href="{% url 'main:home' %}"><span id="span">KAYSA SWA</span></a>
                <ul></ul>
                    <a href="{% url 'main:home' %}">
                    <button id="buttonpink" type="button" class="btn btn-secondary">HOME</button></a>

                    <a href="{% url 'main:about' %}">
                    <button id="buttonorange" type="button" class="btn btn-secondary">ABOUT ME</button></a>

                    <a href="{% url 'main:educations' %}">
                    <button id="buttonpink" type="button" class="btn btn-secondary">EDUCATIONS</button></a>

                    <a href="{% url 'main:experiences' %}">
                    <button id="buttonorange" type="button" class="btn btn-secondary">EXPERIENCES</button></a>

                    <a href="{% url 'main:project' %}">
                    <button id="buttonpink" type="button" class="btn btn-secondary">PROJECT</button></a>

                    <a href="{% url 'main:contact' %}">
                    <button id="buttonorange" type="button" class="btn btn-secondary">CONTACT</button></a>

            </h1>

        {% endblock header1 %}
    
        {% block content %}

        <h2 class="h2">
            <div class="card-deck">
                <div class="card" id="card1">
                    <div class="card-body">
                     <h5 class="card-title" id="font-card">STORY1</h5>
                    <p class="card-text"id="p">Let's take a look on my first website.</p>
                    <a href="{% url 'main:story1' %}" class="btn btn-secondary" id="buttonpink">LET'S GO</a>
                    </div>
                </div>
            
                <div class="card" id="card1">
                    <div class="card-body">
                        <h5 class="card-title" id="font-card">STORY5</h5>
                        <p class="card-text"id="p">My Courses</p>
                        <a href="{% url 'story5:courses' %}" class="btn btn-secondary" id="buttonpink">LET'S GO</a>
                    </div>
                </div>

                <div class="card" id="card1">
                    <div class="card-body">
                        <h5 class="card-title" id="font-card">STORY6</h5>
                        <p class="card-text"id="p">The Event of TDD</p>
                        <a href="{% url 'Events:Events' %}" class="btn btn-secondary" id="buttonpink">LET'S GO</a>
                    </div>
                </div>

        </div>
        </h2>

        {% endblock content %}

        {% block header3 %}

        <h3 class="h3">FIND ME HERE
            <script src="https://kit.fontawesome.com/56fc67844f.js" crossorigin="anonymous"></script>
                <div class="center">
                    <a href="https://www.instagram.com/kaysasy_/" target="_blank">
                        <i class="fab fa-instagram" id="link2"></i></a>
    
                        <a href="https://id.linkedin.com/in/kaysa-swa-20814b1a4" target="_blank">
                        <i class="fab fa-linkedin"  id="link1"></i></a>
                        
                        <a href="https://mail.google.com/mail/u/0/#inbox?compose=NZVHGDkdRDwnxgckKZgqFpxfFnMBqkGrVcSHCSVPWVZvKrMTHhQHhLjRXBvCxjmkFjVNpg" target="_blank">
                        <i class="fas fa-envelope" id="link1"></i></a>
                        
                        <i class="fab fa-line" id="link1"></i>
                </div>
        </h3>

        {% endblock header3 %}
  

            </h4>
                
            </h4>
        </body>
</html>